### ISSUE TITLE
UnboundLocalError  with nxos_snmp_community

### ISSUE THREAD

**Issue by EvgeniyV** [jedelman8/pycsco#26]
Hi all,
In simple snmp configuration task 

```
      - nxos_snmp_community: host={{ inventory_hostname }} 
                             community='string' access='ro'
```

i've got this exception

```
Traceback (most recent call last):
  File "/home/varfolomeiev/.ansible/tmp/ansible-tmp-1451558549.38-5943174160222/nxos_snmp_community", line 1833, in <module>
    main()
  File "/home/varfolomeiev/.ansible/tmp/ansible-tmp-1451558549.38-5943174160222/nxos_snmp_community", line 209, in main
    results['new'] = snmp.get_snmp_community(device, community)
UnboundLocalError: local variable 'results' referenced before assignment

```

**Comment by jedelman8** [comment]
Thanks.  I just fixed this for the snmp modules.  Can pull down the updates (from the ansible repo) and try again?  Again, please open these issues on the nxos-ansible repo.  This one has nothing to do with `pycsco`.

On a side note, we are currently re-factoring the modules and you should see improvements over the next  few weeks.  Please keep finding these bugs though...very much appreciated.

**Comment by EvgeniyV** [comment]
thanks  - your fix working fine
